//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int codEmpresa { get; set; }
        public string nombre { get; set; }
        public string sector { get; set; }
        public string contacto { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
    }
}
